blas_impl:
  - mkl                        # [x86 or x86_64]
  - openblas                   # [not win]
c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2017                     # [win]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2017                     # [win]
fortran_compiler:
  - gfortran                   # [linux or osx]
  - intel-fortran              # [win]
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.10.sdk        # [osx and x86_64]
  - /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk  # [osx and arm64]
cran_mirror:
  - https://cran.r-project.org
c_compiler_version:        # [linux or osx]
  - 11.2.0                 # [linux]
  - 14                     # [osx]
cxx_compiler_version:      # [linux or osx]
  - 11.2.0                 # [linux]
  - 14                     # [osx]
fortran_compiler_version:
  - 2022.1.0                     # [win]
  - 11.2.0                       # [osx or linux]
clang_variant:
  - clang
glib:
  - 2
lua:
  - 5
macos_min_version:
  - 10.9  # [osx and x86_64]
  - 11.1  # [osx and arm64]
macos_machine:
  - x86_64-apple-darwin13.4.0  # [osx and x86_64]
  - arm64-apple-darwin20.0.0   # [osx and arm64]
MACOSX_DEPLOYMENT_TARGET:
  - 10.9  # [osx and x86_64]
  - 11.1  # [osx and arm64]
numpy:
  # python 3.8
  - 1.21
  # python 3.9
  - 1.21
  # python 3.10
  - 1.21
  # python 3.11
  - 1.23
libprotobuf:
  - 3.20.3
python:
  - 3.8
  - 3.9
  - "3.10"
  - "3.11"
r_base:
  - 3.5
sqlite:
  - 3
cross_compiler_target_platform:
  # - win-32                     # [win]
  - win-64                     # [win]
target_platform:
  - win-64                     # [win]
vc:
  - 14                         # [win]
zlib:
  - 1.2
extend_keys:
  - pin_run_as_build
  - ignore_version
  - extend_keys
  - ignore_build_only_deps
ignore_build_only_deps:
  - numpy
  - python
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
channel_targets:
  - conda-forge
  - bioconda
  - defaults
zip_keys:
  -
    - python
    - numpy
zstd:
  - 1.5.2