c_compiler: clang_osx-64
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: clangxx_osx-64
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.10.sdk
extend_keys:
  - pin_run_as_build
  - ignore_version
  - extend_keys
  - ignore_build_only_deps
fortran_compiler:
  - gfortran_osx-64
ignore_build_only_deps:
  - numpy
  - python
lua: '5'
numpy: '1.16'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '3.7'
r_base: '3.5'
target_platform: osx-64