package:
  name:
  version:

source:
  git_url: https://bitbucket.org/genomicepidemiology/kma.git
  script: cd kma && make

build:
  number: 0

requirements:
  build:
    - pip

  run:
    - notebook
    - nglview
    - jupyter_contrib_nbextensions
    - nbexamples