# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /Users/malhal/dev/kma/conda, last modified Mon Jun 19 11:29:00 2023
# ------------------------------------------------

package:
  name: kma
  version: 1.4.9
source:
  url: https://bitbucket.org/genomicepidemiology/kma/get/1.4.9.tar.gz
build:
  number: '0'
  string: h254f028_0
requirements:
  build:
    - ca-certificates 2023.5.7 h8857fd0_0
    - cctools_osx-64 973.0.1 h5676edf_13
    - clang 16.0.6 hc177806_0
    - clang-16 16.0.6 default_h762fdd7_0
    - clang_osx-64 16.0.6 h8787910_0
    - clangxx 16.0.6 default_h762fdd7_0
    - compiler-rt 16.0.6 he1888fc_0
    - compiler-rt_osx-64 16.0.6 he1888fc_0
    - icu 72.1 h7336db1_0
    - ld64_osx-64 609 hbfe4790_13
    - libclang-cpp16 16.0.6 default_h762fdd7_0
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm16 16.0.6 he4b1e75_0
    - libxml2 2.11.4 hd95e348_0
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 he4b1e75_0
    - make 4.3 h22f3db7_1
    - openssl 3.1.1 h8a1eda9_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.2 hbc0c0cd_6
  host:
    - libzlib 1.2.13 h8a1eda9_5
    - zlib 1.2.13 h8a1eda9_5
  run:
    - libzlib >=1.2.13,<1.3.0a0
    - zlib
test:
  commands:
    - kma -h | grep KMA >/dev/null
about:
  home: https://bitbucket.org/genomicepidemiology/kma
  license: Apache-2.0
  summary: KMA is mapping a method designed to map raw reads directly against redundant
    databases, in an ultra-fast manner using seed and extend.
extra:
  copy_test_source_files: true
  final: true
  identifiers:
    - doi:10.1186/s12859-018-2336-6
