{% set name = "kma" %}
{% set version = "1.4.9" %}

package:
  name: kma
  version: 1.4.9

source:
  url: https://bitbucket.org/genomicepidemiology/kma.git

build:
  number: 1

requirements:
  host:
    - zlib
  build:
    - make
  run:
    - zlib

test:
  commands:
  - kma -h