package:
  name: kma
  version: 1.4.9

source:
  url: https://bitbucket.org/genomicepidemiology/kma.git

build:
  number: 2

requirements:
  host:
    - python
    - setuptools
  build:
   - python
    - numpy
run:
  - python
  - numpy
test:
  commands:
  - kma -h