package:
  name: kma
  version: 1.4.9

source:
  url: https://bitbucket.org/genomicepidemiology/kma.git

build:
  number: 2

requirements:
host:
  - python
  - setuptools

run:
  - python

test:
  commands:
  - kma -h