package:
name: kmergenetyper
version: 1.0.13

source:
  url: https://github.com/genomicepidemiology/kmergenetyper/archive/refs/tags/v1.0.16.tar.gz

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - kma >=1.4.9
    - python >=3.6
  host:
    - python >=3.6
    - pip
    - kma >=1.4.9
    - numpy >=1.23.2
  run:
    - python >=3.6
    - kma >=1.4.9
