package:
  name:
  version:

source:
  git_url: https://bitbucket.org/genomicepidemiology/kma.git
  script: cd kma && make

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed . -v

requirements:
  build:
    - pip
    - numpy >=1.13

  run:
    - numpy >=1.13
    - notebook
    - nglview
    - jupyter_contrib_nbextensions
    - nbexamples