package:
  name: kmergenetyper
  version: 1.0.13

source:
  url: https://github.com/genomicepidemiology/kmergenetyper/archive/refs/tags/v1.0.16.tar.gz

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - python ==3.8
    - kma >=1.4.9
  host:
    - python ==3.8
    - kma >=1.4.9
  run:
    - python ==3.8
    - kma >=1.4.9