package:
  name:
  version:

source:
  git_url: https://bitbucket.org/genomicepidemiology/kma.git
  script: cd kma && make

requirements:
  build:
    - python
    - numpy>=1.11.1,<1.16.0
  run:
    - python
    - numpy>=1.11.1,<1.16.0
