on:
  push:
    branches: [ conda ]
  jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: publish-to-conda
        uses: paskino/conda-package-publish-action@master
        with:
          subDir: 'conda'
          channels: 'conda-forge -c ccpi -c paskino'
          AnacondaToken: ${{ secrets.SATYAKP_CONDA_AUTH_TOKEN }}
          convert_osx: true