on:
  workflow_dispatch:

jobs:
  conda-noarch:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Make conda yaml
        run: |
          pip install PyYAML
          python make_conda_linux.py

      - name: Extract tag and update version.yaml
        run: |
          TAG=$(git --tags --abbrev=0)
          echo "Updating version.py with tag: $TAG"
          echo "version: $TAG" > version.py
          git add version.py
          git commit -m "Update version.yaml with tag $TAG" || true
          git tag -a -f $TAG -m "Tagging version $TAG" || true
          git push origin HEAD:main --follow-tags

      - name: Push to Repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Commit message"
          git push

        env:
          GH_TOKEN: ${{ secrets.SATYAKP_CONDA_AUTH_TOKEN }}

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: envs/linux-build.yml

      - name: build conda package
        run: |
          conda install -c anaconda anaconda-client
          conda mambabuild conda -c conda-forge -c bioconda --output-folder .

      - name: upload conda package
        run: |
          anaconda -t ${{ secrets.SATYAKP_CONDA_AUTH_TOKEN }} upload --label main noarch/*.tar.bz2