  name: automatic-version-release1
  on:
    pull_request:
      branches:
      - 'main'
  jobs:
    auto-tag-release:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Release new versions using AutoTagBot
          uses: snapserv/action-autotagbot@master
          with:
            api_token: '${{ secrets.PERSONAL_TOKEN }}'
            source_file: 'version.json'
            version_pattern: '"version"\s*:\s*"(?<version>[0-9.]+)"'
            tag_format: 'v{version}'
