name:
     siri
on:
  push:
    branches:
      [ main ]
jobs:
   release:
            name: "prasu1"
            runs-on: "ubuntu-latest"
            steps:
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  prerelease: false
    
