  name: automatic-version-release1
  on:
    pull_request:
      branches:
      - 'main'
  jobs:
    auto-tag-release:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Release new versions using AutoTagBot
          uses: snapserv/action-autotagbot@master
          with:
            api_token: '${{ secrets.PERSONAL_TOKEN }}'
            source_file: 'version.json'
            version_pattern: '"version"\s*:\s*"(?<version>[0-9.]+)"'
            tag_format: 'v{version}'
    docker:
      runs-on: ubuntu-latest
      steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: satyakp/vc:latest
            secrets: |
              GIT_AUTH_TOKEN=${{ secrets.PERSONAL_TOKEN }}
