  name: automatic-version-release1
  on:
    push:
      branches:
        - tester
  jobs:
    conda:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: publish-to-conda
        uses: paskino/conda-package-publish-action@master
        with:
          subDir: 'conda'
          channels: '-c bioconda -c defaults'
          AnacondaToken: ${{ secrets.SATYAKP_CONDA_AUTH_TOKEN }}
          publish: true
          test_all: true