name: conda-automatic-release
on:
  push:
    branches:
      - development
jobs:
  conda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: publish-to-conda
        uses: paskino/conda-package-publish-action@master
        with:
          subDir: 'conda'
          channels: '-c satyakp'
          AnacondaToken: ${{ secrets.SATYAKP_CONDA_AUTH_TOKEN }}
          publish: true
          test_all: true